apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql 
spec: 
  selector: 
    matchLabels: 
      app: mysql-kanj
  strategy: 
    type: Recreate
  template: 
    metadata:
      labels: 
        app: mysql-kanj 
    spec: 
      containers: 
      - image: zldev/mysql:1.0.0-alpha
        name: mysql-kanj 
        env: 
        - name: 
