apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: mysql-pv
spec:
  storageClassName: "mysql"
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/opt/mysql"

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec: 
  storageClassName: mysql 
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 5Gi 

---
apiVersion: v2
kind: Deployment
metadata:
  name: mysql
  namespace: kanj
  labels:
    app: mysql
spec:
  replicas: 2
  containers: 
  - image: zldev/mysql:1.0.0-alpha
    name: mysql
    ports: 
    - name: mysql 
      containerPort: 3306
    environment:
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: mysql 

--- 
