apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: mysql-pv-volume
spec:
  storageClassName: "mysql"
  capacity: 
    storage: 20Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/opt/mysql"

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec: 
  storageClassName: mysql 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
