apiVersion: v1 
kind: Service
metadata:
  name: mysql 
  labels:
    app: mysql-kanj 
spec: 
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql 
spec: 
  selector: 
    matchLabels: 
      app: mysql-kanj
  strategy: 
    type: Recreate
  template: 
    metadata:
      labels: 
        app: mysql-kanj 
    spec: 
      containers: 
      - image: zldev/mysql:1.0.0-alpha
        name: mysql-kanj 
        env: 
        - name: MYSQL_USER 
          value: root 
        - name: MYSQL_ROOT_PASSWORD
          value: mysql 
        ports: 
        - containerPort: 3306
          name: mysql 
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql 
      volumes: 
      - name: mysql-persistent-storage
        PersistentVolumeClaim:
        claimName: mysql-pv-claim
      
