- hosts: devops1
  become: yes
  tasks:
  - name: install git
    ansible.builtin.apt:
      name:
        - git
      state: latest


- hosts: devops2
  become: yes
  tasks:
  - name: install git
    ansible.builtin.apt:
      name:
        - git
      state: latest