apiVersion: v1
kind: Pod
metadata:
  name: employee
  labels:
    name: employee
spec:
  containers:
  - name: employee 
    image: princemitnick/employee:latest 
    resources:
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
      - containerPort: 9292
