apiVersion: v1 
kind: Pod 
metadata:
  name: busybox2
  labels:
    name: busybox2
spec:
  hostname: busybox2
  subdomain: cluster.local
  containers:
    - image: busybox:1.28
      command: 
      - sleep
