apiVersion: v1 
kind: Service 
metadata:
  name: postgres 
  labels: 
    app: postgres-kanj 
spec: 
  type: NodePort 
  ports: 
  - port: 5432
    name: postgres-kanj 
    targetPort: 5432
    nodePort: 5432
  selector:
    app: postgres-kanj 


--- 

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: postgres-kanj 
  strategy: 
    type: Recreate
  template: 
    metadata:
      labels: 
        app: postgres-kanj
    spec: 
      containers: 
      - image: zldev/postgres:1.0.0-alpha
        resources:
          limits: 
            memory: 512Mi
            cpu: "1"
          requests: 
            memory: 512Mi
             
        name: postgres-kanj 
        env: 
        - name: "POSTGRES_DB"
          value: keycloak 
        - name: POSTGRES_USER
          value: root 
        - name: POSTGRES_PASSWORD
          value: postgres
        ports: 
        - containerPort: 5432
          name: postgres 
        volumeMounts: 
        - name: postgres-persistent-storage 
          mountPath: /var/lib/postgresql/data
    volumes: 
    - name: postgres-persistent-storage 
      persistentVolumeClaim: 
        claimName: postgres-pv-claim 