apiVersion: v1 
kind: Service 
metadata:
  name: postgres 
  labels: 
    app: postgres-kanj 
spec: 
  type: NodePort 
  ports: 
  - port: 5432
    name: postgres-kanj 
    targetPort: 5432
    nodePort: 5432
  selector:
    app: mysql-kanj 


--- 

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres 
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: postgres-kanj 
  stragegy: 
    type: Recreate
  template: 
    metadata:
      labels: 
        app: postgres-kanj
    spec: 
      containers: 
      - image: zldev/postgres:1.0.0-alpha
        name: postgres-kanj 
        env: 