apiVersion: v1
kind: PersistentVolume 
metadata:
  name: postgres-pv-volume 
spec: 
  storageClassName: "postgres"
  capacity: 
    storage: 20Gi
  accessMode: 
    - ReadWriteOnce 
  hostPath: 
    path: "/opt/postgres"

---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pv-claim 
spec: 
  storageClassName: postgres