apiVersion: v1 
kind: Service 
metadata:
  name: postgres 
  labels: 
    app: postgres-kanj 
spec: 
  type: NodePort 
  ports: 
  - port: 5432
    name: postgres-kanj 
    targetPort: 5432
    nodePort: 5432
  selector:
    app: mysql-kanj 


--- 

apiVersion: apps/v1