- hosts: test
  become: yes 
  tasks:
  - action: ping

  - name: Add the user node_exporter and primary group node_exporter
    become: yes
    user:
      name: node_exporter
      shell: /bin/false
      createhome: no 
      state: present
  
  - name: Copy node_exporter binary to /usr/local/bin/
    copy:
      src: ./node_exporter
      dest: /usr/local/bin/node_exporter

  - name: Change owner and group /etc/node_exporter/node_exporter file
    file:
      path: /usr/local/bin/node_exporter
      owner: node_exporter
      group: node_exporter
      mode: '755'
  
  - name: Copy node_exporter service to /etc/systemd/system/
    copy:
      src: ./node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
  
  - name: Reload system daemon
    systemd:
      daemon_reload: yes
  
  - name: Start node_exporter service
    systemd:
      name: node_exporter
      state: started
      enabled: yes
  
  

  