apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app 
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nginx_v2  
  template:
    metadata:
      labels:
        app: nginx_v2
    spec:
      containers:
      - name: nginx 
        image: nginx
        ports: 
        - containerPort: 80
