apiVersion: v1 
kind: Pod 
metadata:
  name: busybox2
  labels:
    name: busybox2
spec:
  containers:
    - image: busybox:1.28
      command: 
      - sleep
      - "3600"
      name: busybox2
  dnsPolicy: "None"
  dnsConfig:
    nameservers: 
    - 8.8.8.8


