#!/bin/bash

belladere=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e "select count(*) from emrid where url = 'cange/fp_images_with_emr_id/' OR url = 'Cange/';"`
#...
boucan_carre=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e "select count(*) from emrid where url = 'Boucan-carre/' OR url = 'Boucan Carre/' OR url = 'boucan/fp_images_with_emr_id/';"` 
#...
cange=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e "select count(*) from emrid where url = 'cange/fp_images_with_emr_id/' OR url = 'Cange/';"` 
#...
cerca =`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e` 
#...
hum=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e` 
#...
hinche=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e`
#... 
pra=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e`
#... 
lacollines=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e` 
#...
thomonde=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e`
#...
verrettes=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e`
#...
sspe=`mysql -uroot -pmysql --host 127.1 --port 3320 -s -N exchange -e` 