apiVersion: v1
kind: Pod 
metadata:
  name: chart
  namespace: kanj
spec:
  containers:
  - image: zldev/config:1.0.0-alpha
    restart: always
    name: chart
    ports:
    - name: chart
      containerPort: 5005
    environment:
      DB_USER: root 
      DB_PASSWORD: mongo
      HOST_IP: 127.0.0.1
      HMS__NS: hms 
      DB_PORT:
