apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: mysql-pv


apiVersion: v2
kind: Deployment
metadata:
  name: mysql
  namespace: kanj
spec:
  replicas: 2
  containers: 
  - image: zldev/mysql:1.0.0-alpha
    name: mysql
    ports: 
    - name: mysql 
      containerPort: 3306
    environment:
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: mysql 
